export const GET_CHAT_HISTORY = "GET_CHAT_HISTORY";
export const GET_USERS_LIST = "GET_USERS_LIST";
export const CHANGE_ACTIVE = "CHANGE_ACTIVE";
export const SET_ROOM_ID = "SET_ROOM_ID";
export const CHANGE_TYPING = "CHANGE_TYPING";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const DELETE_CHAT = "DELETE_CHAT";
export const MESSAGE_LOOKED = "MESSAGE_LOOKED";