export const SHOW_LOGIN_SIGNUP_MODAL = "SHOW_LOGIN_SIGNUP_MODAL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const ERROR = "ERROR";

export const ALERT_SET_ACTION = "ALERT_SET_ACTION";
export const ALERT_ACTION = "ALERT_ACTION";

export const CHANGE_AVATAR_SUCCESS = "CHANGE_AVATAR_SUCCESS";
export const CHANGE_USERNAME_SUCCESS = "CHANGE_USERNAME_SUCCESS";

export const  RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";